In [11]:
import pandas as pd

parameter_names = [
    "snoring rate",
    "respiration rate",
    "body temperature",
    "limb movement",
    "blood oxygen",
    "eye movement",
    "sleeping hours",
    "heart rate",
    "stress level"
]

data = pd.read_csv('SaYoPillow.csv')
data.columns=parameter_names

In [12]:
data

snoring rate  respiration rate  body temperature  limb movement  \
0          93.800            25.680            91.840         16.600   
1          91.640            25.104            91.552         15.880   
2          60.000            20.000            96.000         10.000   
3          85.760            23.536            90.768         13.920   
4          48.120            17.248            97.872          6.496   
..            ...               ...               ...            ...   
625        69.600            20.960            92.960         10.960   
626        48.440            17.376            98.064          6.752   
627        97.504            27.504            86.880         17.752   
628        58.640            19.728            95.728          9.728   
629        73.920            21.392            93.392         11.392   

     blood oxygen  eye movement  sleeping hours  heart rate  stress level  
0          89.840         99.60           1.840       74.20             3  
1          89.552         98.88           1.552       72.76             3  
2          95.000         85.00           7.000       60.00             1  
3          88.768         96.92           0.768       68.84             3  
4          96.248         72.48           8.248       53.12             0  
..            ...           ...             ...         ...           ...  
625        90.960         89.80           3.440       62.40             2  
626        96.376         73.76           8.376       53.44             0  
627        84.256        101.88           0.000       78.76             4  
628        94.592         84.32           6.728       59.32             1  
629        91.392         91.96           4.088       63.48             2  

[630 rows x 9 columns]

In [13]:
data = data.drop(['body temperature', 'limb movement', 'eye movement'], axis=1)


In [14]:
# Import necessary libraries
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

X = data[[
    "snoring rate",
    "respiration rate",
    "blood oxygen",
    "sleeping hours",
    "heart rate",
]]
y = data['stress level']

In [15]:
# Split the data into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=420)

# Create an XGBoost classifier
model = xgb.XGBClassifier()

# Fit the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Calculate and print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Display the confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.9841269841269841
Confusion Matrix:
[[20  0  0  0  0]
 [ 0 37  0  0  0]
 [ 0  1 20  0  0]
 [ 0  0  1 23  0]
 [ 0  0  0  0 24]]


In [16]:
import joblib
# Save the trained XGBoost model to a file
joblib.dump(model, 'xgboost_model.pkl')
# Load the saved model from the file
loaded_model = joblib.load('xgboost_model.pkl')

# Now you can use 'loaded_model' to make predictions as you would with the original model
loaded_predictions = loaded_model.predict(X_train)